#!/usr/bin/env python3
#
# Gramps - a GTK+/GNOME based genealogy program
#
# Copyright (C) 2026  Doug Blank
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

"""
Generate the _CHN_YEAR_INFOS lookup table for gramps/gen/lib/gcalendar.py.

Uses the tyme4py library (MIT licence, https://github.com/6tail/tyme4py)
to produce a 17-bit integer per Chinese Lunar year encoding:

  bits 15–4 : 30-day flag for regular months 1–12 (bit 15 = month 1, …)
  bits  3–0 : leap-month index (0 = no leap, 1–12 = which month is followed
               by a leap month)
  bit    16 : 1 if the leap month has 30 days, 0 if 29

Usage:
    python3 scripts/gen_chinese_lunar_table.py [START [END]]

    START  first Chinese Lunar year to include  (default: 1)
    END    last  Chinese Lunar year to include  (default: 9999)

Output is printed to stdout and can be redirected to a file for review
before copying the relevant sections into gcalendar.py.

Requirements:
    pip install tyme4py
"""

import sys

# -------------------------------------------------------------------------
#
# Standard Python modules
#
# -------------------------------------------------------------------------
import textwrap


def _encode_year(year: int) -> int:
    """Return the 17-bit encoding for one Chinese Lunar year via tyme4py."""
    from tyme4py.lunar import LunarYear

    ly = LunarYear.from_year(year)
    leap_month = ly.get_leap_month()
    months = ly.get_months()

    info = leap_month  # bits 3-0
    for m_obj in months:
        days = m_obj.get_day_count()
        is_leap = m_obj.is_leap()
        m = abs(m_obj.get_month_with_leap())
        if is_leap:
            if days == 30:
                info |= 1 << 16
        else:
            if days == 30:
                info |= 1 << (16 - m)
    return info


def _get_new_year_gregorian(year: int) -> tuple[int, int, int]:
    """Return the proleptic-Gregorian (y, m, d) of Lunar year 1/1/1."""
    from tyme4py.lunar import LunarYear

    ly = LunarYear.from_year(year)
    first_day = ly.get_first_month().get_first_day()
    sd = first_day.get_solar_day()
    return sd.get_year(), sd.get_month(), sd.get_day()


def _gregorian_sdn(y: int, m: int, d: int) -> int:
    """Minimal Gregorian-to-SDN identical to gcalendar.gregorian_sdn."""
    if m <= 2:
        m += 12
        y -= 1
    century = y // 100
    return (
        (365 * y)
        + (y // 4)
        - (y // 100)
        + (y // 400)
        + ((306 * (m + 1)) // 10)
        + d
        - 32045
    )


def generate(start: int = 1, end: int = 9999) -> None:
    """Print the table lines and anchor constants for gcalendar.py."""
    try:
        from tyme4py.lunar import LunarYear  # noqa: F401
    except ImportError:
        sys.exit("tyme4py is not installed.  Run: pip install tyme4py")

    gy, gm, gd = _get_new_year_gregorian(start)
    start_sdn = _gregorian_sdn(gy, gm, gd)

    print(f"# Generated by scripts/gen_chinese_lunar_table.py")
    print(f"# tyme4py used as data source (MIT licence)")
    print(f"# Covers Chinese Lunar years {start}–{end}")
    print()
    print(f"_CHN_BASE_YEAR = {start}")
    print(f"_CHN_START_SDN = gregorian_sdn({gy}, {gm}, {gd})  # Lunar {start}/1/1")
    print()
    print(f"_CHN_YEAR_INFOS = [")

    COLS = 5  # entries per line
    entries = []
    for year in range(start, end + 1):
        info = _encode_year(year)
        entries.append((year, info))
        if year % 100 == 0:
            print(f"    # {year}", file=sys.stderr)

    for i, (year, info) in enumerate(entries):
        comma = "," if i < len(entries) - 1 else ""
        if year % COLS == start % COLS:
            # Start of a visual group of COLS
            suffix = f"  # {year}"
        else:
            suffix = ""
        print(f"    {hex(info)}{comma}{suffix}")

    print("]")
    print()
    print(
        f"# _CHN_YEAR_INFOS has {len(entries)} entries "
        f"covering years {start}–{end}."
    )


if __name__ == "__main__":
    args = sys.argv[1:]
    start = int(args[0]) if len(args) >= 1 else 1
    end = int(args[1]) if len(args) >= 2 else 9999
    generate(start, end)
