register(VIEW, 
         id = 'citationtreeview',
         name = _("Citation Tree View"),
         description =  _("A view displaying citations in a tree format."),
         version = '1.0',
         gramps_target_version = '3.4',
         status = STABLE,
         fname = 'citationtreeview.py',
         authors = [u"Tim G L Lyons", u"Nick Hall"],
         authors_email = [""],
         category = ("Citations", _("Citations")),
         viewclass = 'CitationTreeView',
         stock_icon = 'gramps-tree-group',
  )
