register(VIEW, 
         id    = 'fanchartview',
         name  = _("Fan Chart View"),
         category = ("Charts", _("Charts")),
         description =  _("The view showing relations through a fanchart"),
         version = '1.0',
         status = UNSTABLE,
         fname = 'fanchartview.py',
         authors = [u"Douglas S. Blank"],
         authors_email = ["doug.blank@gmail.com"],
         viewclass = 'FanChartView',
  )
